{% set name = "metagenlab_libs" %}
{% set version = "1.0.2" %}

package:
      name: {{ name|lower }}
      version: {{ version }}

source:
    url: https://github.com/metagenlab/metagenlab_libs/archive/refs/tags/{{version}}.tar.gz
    sha256: 813491bc262507ec017fbf0c7f61c0432944bf7232b29f2316d3b6717893a40a 

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

tests:
  imports:
     - metagenlab_libs

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - matplotlib
    - ete3>=3
    - biopython>=1.77
